### ISSUE TITLE
prepare environments for github CI-Based OSS build

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO#10]
prepare environments for github CI-Based OSS build

We learned now how all works together. It's time now to automate the OSS build.
Currently the biggest problem is that changes we do don't reach the OSS version. Therefore all changes must be done for OSS version, and Bosch-Internal-Version is "just" an extension to OSS version.

Goal is to build and release with 0.6.0 Version the first time also a pure OSS version built by github CI.
This will be then the first version we will bring to the RobotFramework Community.

Therefore:
- [x] 1. cleanup all partly redundant cloneall*, build* and install* scripts.
   Expected:
   for each 1 Windows, 1 Linux script, maybe for cloneall only one script?
   install* : 1 Windows, one Linux script if required. default "no proxy", alternative ```--use_cntlm```. No other proxy option.

- [x] 2. remove wget completely and use curl.

- [x] 3. Base for all scripts must be github.
   Therefore Apertis build directory must hold only extension/or alternative configuration. E.g. scripts can load repository config by means of ```--configfile=.....```

- [x] 4. Run Apertis based CI with new scripts
- [x] 5. Run github CI with new scripts for Windows10 and Ubuntu.

**Comment by ngoan1608** [comment]
Hi Thomas,
Hi Nguyen,


I add some points need to be improved bases on my initial PR #16 :
- [ ] The scripts (build, clone, install, tag) should be up-to-date with Gitlab repo.
- [ ] Include [robotframework-documentation](https://github.com/test-fullautomation/robotframework-documentation) in build jobs
- [x] Optimize Windows build job by specifying required texlive packages instead of install collections => need to be discussed for the conclusion 

Thank you

**Comment by test-fullautomation** [comment]
Hi Nguyen,
please look into this additional open points.
Thank you,
 Thomas

**Comment by ngoan1608** [comment]
Hi Thomas,

The execution time of Windows job has been improved (from >1hour to ~21mins) as new workflow:
https://github.com/test-fullautomation/RobotFramework_AIO/actions/runs/3655119795/jobs/6176156241

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
very good! (The execution time reduction)
