### ISSUE TITLE
robotframework-dbus and robotframework-qconnect-winapp integration

### ISSUE THREAD

**Issue by ngoan1608** [test-fullautomation/RobotFramework_AIO#112]
Hi Thomas,

As @milanac030988's request, `robotframework-dbus` and `robotframework-qconnect-winapp` libraries should be parts of Robotframework AIO.
Please help to create appropriate repos in Gitlab for mirroring and label (set milestone) this ticket to which version for this integration.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi Cuong,
as written in my Email both I planned for 0.9.0.
This gives us time for selftest and good documentation before we release ist.
Possible users can install it for 0.8.0 with our support manually.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
@milanac030988 : what is the status of both libraries?
