### ISSUE TITLE
Insufficient workspace permissions

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/RobotFramework_AIO#114]
After installation of RobotFramework_AIO_0.8.1.2-0_amd64.deb it is not possible any more to save the workspace in VS Codium (already the autosave after a folder has been added to the workspace, does not work).

Error message:

`Failed to save 'RobotTest.code-workspace'. Insufficient permissions.`

**Comment by test-fullautomation** [comment]
@HolQue : What is the status of this issue and related #122

**Comment by HolQue** [comment]
Hi Thomas,

retest with osd5:build
https://gitlab-apertispro.boschdevcloud.com/robotframework-aio/main/robotframework_aio/-/jobs/2715946

Issue solved, workspace is available and can be saved.
