### ISSUE TITLE
deb file couldn't be accessed

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/RobotFramework_AIO#115]
At end of an installation of a deb file the following error message appears in console:

```
N: Download is performed unsandboxed as root as file '/home/... .deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by HolQue** [comment]
Addendum:

The second error message

`E: Sub-process /usr/bin/dpkg returned an error code (1)`

also occurred at end of deinstallation with

`sudo apt-get remove robotframework-aio`

**Comment by HolQue** [comment]
Addendum:

I moved the deb file to `/tmp` folder and repeated the installation, but the error message still occur:

```
N: Download is performed unsandboxed as root as file '/tmp/RobotFramework_AIO_0.8.1.2-0_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by HolQue** [comment]
Permissions:

`-rwxrwx---  1 <it's me> <it's me> 535M Jun  8 09:05 RobotFramework_AIO_0.8.1.2-0_amd64.deb`

Is this OK?

**Comment by ngoan1608** [comment]
Hi Holger,

Please refer my comment as our discussion:
1) The first message is just the notice that `_apt` user try to the directory which `*.deb` fil is located (user folder).
It is not problem with the installation. We can avoid this notice by locating `*.deb` file in public directory (other than user location) such as '/tmp'.
I have referred some useful discussion as below:
https://www.reddit.com/r/linux4noobs/comments/ux6cwx/installation_errors_on_deb_files_apt/
https://askubuntu.com/questions/1403337/download-is-performed-unsandboxed-as-root-as-file

2) The second message is the error related broken packages (previous failed installation of other packages).
You can fix it by reconfiguring package with `sudo dpkg --configure -a`

Please try and give your feedback.

Thank you,
Ngoan

**Comment by ngoan1608** [comment]
> Permissions:
> 
> `-rwxrwx--- 1 <it's me> <it's me> 535M Jun 8 09:05 RobotFramework_AIO_0.8.1.2-0_amd64.deb`
> 
> Is this OK?

Hi Holger,

Change permission of `*.deb` does not help. I have tried with it.

Thank you,
Ngoan

**Comment by HolQue** [comment]
Seems that I have a tex problem:

```
:/tmp$ sudo dpkg --configure -a
Setting up tex-common (6.09) ...
Missing head file /usr/share/texlive/texmf-dist/tex/generic/config/language.us.lua: No such file or directory at /usr/sbin/update-language line 139.
dpkg: error processing package tex-common (--configure):
 installed tex-common package post-installation script subprocess returned error exit status 2
Errors were encountered while processing:
 tex-common
```

**Comment by ngoan1608** [comment]
> Addendum:
> 
> I moved the deb file to `/tmp` folder and repeated the installation, but the error message still occur:
> 
> ```
> N: Download is performed unsandboxed as root as file '/tmp/RobotFramework_AIO_0.8.1.2-0_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> ```

Sorry I missed this comment.
Can you try with below command to grant read permission  for other to `*.deb` file?
```
sudo chmod 744 /tmp/RobotFramework_AIO_0.8.1.2-0_amd64.deb
```
Then try to install again.
I am checking from my side about the permission of installer `*.deb` file after buiding.

Thank you,
Ngoan

**Comment by ngoan1608** [comment]
Hi,

Please refer my conclusion about this ticket:
1) Notice message `N: Download is performed unsandboxed as root as file '/home/... .deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)`
  - This notice does not impact to the installation which has been executed successfully.
  - To avoid this notice, the installer `*.deb` file should be placed in the location other than user directory.
  - **_Note: the `*.deb` file which is extracted from `*.zip` file on Windows then copied to Linux for installation has the changed permission (missing read permission for other users).
    The `*.deb` file which is extracted on Linux has granted proper read permission for all users._**

2) The error message `E: Sub-process /usr/bin/dpkg returned an error code (1)`
  - This error due to the broken package(s) (does not related to AIO package) on user machine when run `apt-get install` 
  => should be fixed by user. (remove broken package or reconfigure `dpkg` if requires)

So, there is no change in the implementation.
Please correct me in case I missed somethings.

Thank you,
Ngoan

**Comment by HolQue** [comment]
Hi Ngoan,

you' re right! It's clarified.

Very good hint from you: "_Note: the *.deb file which is extracted from *.zip file on Windows then copied to Linux for installation has the changed permission (missing read permission for other users)._"

Because this is the way I usually go ;-)

**Comment by test-fullautomation** [comment]
Hi Holger,
yes, you must be carefully when copying data from Windows to Linux. Always consider that this changes the rights to the file.
Thank you,
 Thomas
