### ISSUE TITLE
JSON file duplicate?

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/RobotFramework_AIO#116]
The installer RobotFramework_AIO_setup_0.8.1.2.exe installs both:

* `%ROBOTPYTHONPATH%\Lib\site-packages\RobotFramework_TestsuitesManagement\Config\robot_config.json`
  with content: `"Project"         : "Generic",`
* `%ROBOTPYTHONPATH%\Lib\site-packages\RobotFramework_TestsuitesManagement\Config\robot_config.jsonp`
  with content: `"Project"         : "RobotFramework Testsuites",`

Do we still need the file robot_config.json with previous extension?

Hint:
The file robot_config.json is installed to
`%ROBOTPYTHONPATH%\Lib\site-packages\RobotFramework_TestsuitesManagement\Config`
at the very beginning of the installation. Whereas all other files (the Python code and also the file robot_config.jsonp) are installed much later during installation. Maybe handled at very different positions in installation scripts?

The .json file is also installed to:
`%ROBOTTESTPATH%\config\robot_config.json`

But I would expect the .jsonp file here.

**Comment by test-fullautomation** [comment]
There should be only one file as per selection in the installer UI.
The file should have the extension jsonp.

I assume that "generic" was selected. So the file should be called robot_config.jsonp. The content should be "Project, Generic".

**Comment by test-fullautomation** [comment]
solved and merged with #120
