### ISSUE TITLE
Linux control file is not updated with tag-information in case of dev/rel tags

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO#118]
Linux control file is not updated with tag-information in case of dev/rel tags.

[RobotFramework_AIO](https://github.com/test-fullautomation/RobotFramework_AIO/tree/develop)/[config](https://github.com/test-fullautomation/RobotFramework_AIO/tree/develop/config)/[build](https://github.com/test-fullautomation/RobotFramework_AIO/tree/develop/config/build)/[dpkg_build](https://github.com/test-fullautomation/RobotFramework_AIO/tree/develop/config/build/dpkg_build)

**Comment by test-fullautomation** [comment]
@ngoan1608 : This is solved, correct?

**Comment by ngoan1608** [comment]
Hi Thomas,

This ticket is not processed. I will check ang implement it.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi Ngoan,
O.K. this would be good to have for 0.9.0.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
duplicate to #158
