### ISSUE TITLE
#113 creates clone error for windows

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO#119]
#113 creates clone error for windows

robotframework_aio/-/jobs/2276335

**Comment by ngoan1608** [comment]
Hi Thomas,

It is git issue due to long filename on windows runner.
I have faced and fixed it before but I wonder it comes back now.

I have configured git again on that Windows runner and re-run the job.
No required change from the source code.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi Ngoan,

O.K. i try again.

Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
@ngoan1608 : this is solved, correct?

**Comment by ngoan1608** [comment]
Hi Thomas,

This ticket can be closed!

Thank you,
Ngoan
