### ISSUE TITLE
Installation incomplete because of missing workspace

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/RobotFramework_AIO#122]
The latest installers (at least setup_RobotFramework_AIO_OSD5Linux_0.7.0.7.deb, setup_RobotFramework_AIO_OSD5Linux_0.8.1.1.deb, and RobotFramework_AIO_0.8.1.3-0_amd64.deb
from https://github.com/test-fullautomation/RobotFramework_AIO/actions/runs/5219911236) do not install the folder

`/home/qth2hi/RobotTest/testcases`

Therefore this workspace file is not available also:

`/home/qth2hi/RobotTest/testcases/RobotTest.code-workspace`

Impact: No workspace is opened after start of VS Codium

What the installer does, is to install a file

`/home/qth2hi/RobotTest/testcases`

with access rights:

`-rw-r--r--  1 root   root          178 Jun  9 10:32 testcases`

and the content, that is expected to be inside

`/home/qth2hi/RobotTest/testcases/RobotTest.code-workspace`

Every follow up installation under these conditions cause:

```
[DONE] Found workspace in ~/RobotTest. Updated only tutorial.
chown: cannot access '~/RobotTest/testcases/RobotTest.code-workspace': Not a directory
```

This can only be healed by

* Deleting the file `~/RobotTest/testcases` manually
* Creating the folder `~/RobotTest/testcases` manually
* Repeating the installation

But the installer should do that.

Regarding the console message: "`Updated only tutorial`": Also the "`documentation`" folder should be updated.

**Comment by HolQue** [comment]
Related to

https://github.com/test-fullautomation/RobotFramework_AIO/issues/114

**Comment by test-fullautomation** [comment]
@HolQue : This is solved, correct?

**Comment by HolQue** [comment]
Hi Thomas,

retest with osd5:build
https://gitlab-apertispro.boschdevcloud.com/robotframework-aio/main/robotframework_aio/-/jobs/2715946

Issue solved, workspace is available and can be saved.
