### ISSUE TITLE
Curious file access during installation of 0.8.2.2

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/RobotFramework_AIO#125]
I deleted the entire `RobotTest` folder. After this I started the installation of RobotFramework_AIO_setup_0.8.2.2.exe (BIOS)

I wanted to check the documentation `RobotTest\documentation\RobotFrameworkAIO_Reference.pdf`

Because of the file was already available I opened this file (while the installer still continues with installing further files).

Some moments later the installer throws an error: An access violation while trying to replace the existing file with this file:

`RobotFramework\python39\Lib\site-packages\RobotFrameworkAIO\RobotFrameworkAIO_Reference.pdf`

I am astonished about this work flow. Why does the installer install a file at the beginning, and some moments later replace this file by another one?

Why not installing the desired version of this file in one single step only?

**Comment by HolQue** [comment]
Addendum:

The installer offers me to repeat the replacement of the PDF file.

Therefore I deleted the PDF file manually and I created an empty text file and gave this empty text file the name "RobotFrameworkAIO_Reference.pdf".

Then I clicked on OK to let the installer repeat the replacement. The installer tells that he extracts something. After the installation has been finished I try to open

RobotTest\documentation\RobotFrameworkAIO_Reference.pdf.

But it's still the empty file. Therefore the installer has not replaced the file.

I repeated the entire installation (without deleting anything before). Now RobotFrameworkAIO_Reference.pdf is updated properly in documentation folder.

**Comment by ngoan1608** [comment]
Hi Holger,

I have tried to preproduce your issue but cannot face this issue.

Here are the steps I followed as your descriptions:
- Delete `RobotTest` folder
- Execute the installer for 0.8.2.2 (BIOS version)
- Open `RobotTest\documentation\RobotFrameworkAIO_Reference.pdf` as soon as it is available (installation is still running)
=> No error with the installation, it run successfully.
- Execute the installer again with `RobotTest\documentation\RobotFrameworkAIO_Reference.pdf` is opened.
- Installer throw an error with 3 options `Abort` (abort the installation), ` Retry`(retry to replace the opened file) and `Ignore`(ignore the opened file without replacement).
- I close `RobotTest\documentation\RobotFrameworkAIO_Reference.pdf` file, remove it. Then create an empty file with same name `RobotFrameworkAIO_Reference.pdf`.
- Click `Retry` to replace the existing one
- The installation completes without further error
- The `RobotTest\documentation\RobotFrameworkAIO_Reference.pdf` file is updated properly.
=> I did not face any error message with `OK` option.

Please correct me in case I missed any step or misunderstood your situation.

Thank you,
Ngoan

**Comment by ngoan1608** [comment]
> I am astonished about this work flow. Why does the installer install a file at the beginning, and some moments later replace this file by another one?
> 
I have also checked the Inno Setup script for Windows installer package, the copy document file is executed only 1 time when initializing the `RobotTest` folder.

The strange behavior that you faced is so curious.

Thank you,
Ngoan

**Comment by HolQue** [comment]
Seems to be a stochastical thing. I face now: The error is not reproducible. I tried several times - without success.

Thank you for cross checking.

Issue can be closed.

**Comment by test-fullautomation** [comment]
:-)
