### ISSUE TITLE
Python module 'pyinstaller' wanted

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/RobotFramework_AIO#130]
The ticket ROBFW-169 is valid again.

I was able to install `pyinstaller` with `pip` on Windows and on Linux - without the problems mentioned in ROBFW-169.

Therefore I ask to add this Python module to the upcoming AIO distribution.

**Comment by test-fullautomation** [comment]
Hi Thong,
please look into this.
Thank you,
 Thomas

**Comment by huavanthong** [comment]
Hi Thomas,

`pyinstaller` module was installed on AIO distribution at commit: c1ed4d2894991bf3c772f73f1e3151023f1921eb by Ngoan following log console on AIO
```
Build Linux package	Build	2023-08-18T12:46:06.8192927Z running install_scripts
Build Linux package	Build	2023-08-18T12:46:07.1550604Z 249 INFO: PyInstaller: 5.13.0
Build Linux package	Build	2023-08-18T12:46:07.1551675Z 249 INFO: Python: 3.9.2
Build Linux package	Build	2023-08-18T12:46:07.1578464Z 252 INFO: Platform: Linux-5.15.0-1042-azure-x86_64-with-glibc2.35
Build Linux package	Build	2023-08-18T12:46:07.1583114Z 252 INFO: wrote /home/runner/work/RobotFramework_AIO/robotframework-dbus/dbus_client_agent.spec
Build Linux package	Build	2023-08-18T12:46:07.2410572Z 335 INFO: UPX is available but is disabled on non-Windows due to known compatibility problems.
Build Linux package	Build	2023-08-18T12:46:07.2422332Z 336 INFO: Extending PYTHONPATH with paths
```
More details log, please refer [here](https://github.com/test-fullautomation/RobotFramework_AIO/actions/runs/5902722475/job/16011271101)

This issues was resolved.  Please help me close this ticket.

Thank you and best regards,
Thong Hua

**Comment by test-fullautomation** [comment]
O.K. thank you for the analysis!
