### ISSUE TITLE
build: change from robotframework:develop to robotframework:develop_6.1

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO#138]
For all platforms:

as per our branching strategy change for our build from robotframework:develop to robotframework:develop_6.1
https://github.com/test-fullautomation/robotframework/tree/develop_6.1

@ngoan1608: Please do this together with @huavanthong . Lot of problems can happen where you might know what is the cause. Exitcode-feature is missing up to now at the develop_6.1 branch. So the build scripts need to be adapted accordingly or (my favorite) @milanac030988 provides a pull-request for this feature. I would immediately merge.
Goal is that our 0.9.0 version runs from develop_6.1 branch.

**Comment by ngoan1608** [comment]
Hi Thomas,
Hi Thong,

1) In case you also switch default branch of [robotframework ](https://github.com/test-fullautomation/robotframework)  to [develop_6.1](https://github.com/test-fullautomation/robotframework/tree/develop_6.1) (default is still `develop` now):
=> No change is required for OSS pipeline, clone and tag job is already implemented to work with default branch of repo.

2) `develop` is kept as default branch, below changes in OSS pipeline are required:
    - Please cherry-pick commit [allow to specify the commit/branch of repos for building](https://github.com/test-fullautomation/RobotFramework_AIO/commit/d016f048bce742a2096a4c20f8750ca64fc8b7b8) from my feature branch [ntd1hc/feat/allow-to-specify-branch-or-commit-of-repos-to-be-built](https://github.com/test-fullautomation/RobotFramework_AIO/compare/develop...ntd1hc/feat/allow-to-specify-branch-or-commit-of-repos-to-be-built) and verify the change. I have implemented the feature to allow specify the branch for cloning in repo configuration file.
    - Update repo configuration file for cloning with `develop_6.1` value for `robotframework`
    - Update repo configuration file for tagging with `develop_6.1` value for `robotframework` (tag tool have already supported to specify branch/commit of repo to tag)

**Required change for BIOS pipeline in both cases:** 
> mirror job for robotframework repo need to be updated to change `upstream branch` from `develop` to `develop_6.1`.


Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi Ngoan,
thank you for the summary.
@huavanthong : please do the required changes.
Thank you,
Thomas

**Comment by huavanthong** [comment]
Hi Thomas,
Cc Ngoan,

Thank you for your info. I would like to verify the workflow after applying the change from the 'develop' branch to 'develop6.1' following info below:
1. **About GitHub:**
* By default, the workspace will clone all repositories with default branch specified for each repository. Therefore, we don't add any value on [repositories.conf ](https://github.com/test-fullautomation/RobotFramework_AIO/blob/develop/config/repositories/repositories.conf ) file.
* If you want to change branch from **develop** (default branch) to **develop_6.1**. Please modify [repositories.conf ](https://github.com/test-fullautomation/RobotFramework_AIO/blob/develop/config/repositories/repositories.conf )file.
```
Old:
robotframework

New:
robotframework=develop_6.1
```
The output log for clone stage can be seen at [here](https://github.com/test-fullautomation/RobotFramework_AIO/actions/runs/6080211139)
```
---- github.robotframework -----------------------------------------
Cloning https://github.com/test-fullautomation/robotframework.git
Cloning into '../robotframework'...
Checking out to 'develop_6.1'
Switched to a new branch 'develop_6.1'
branch 'develop_6.1' set up to track 'origin/develop_6.1'.
From https://github.com/test-fullautomation/robotframework
 * branch                develop_6.1 -> FETCH_HEAD
Already up to date.
>>>> Successfully switched to 'develop_6.1'.
```
2. **About GitLab:** 
If you want to apply for gitlab, we need to update code following info. We will update GITLAB_UPSTREAM_BRANCH
```
old:
GITLAB_UPSTREAM_BRANCH: "develop"

new:
GITLAB_UPSTREAM_BRANCH: "develop_6.1"
```

That's all for my information. If you have any comments, please tell me.

Best regards,
Thong Hua

**Comment by test-fullautomation** [comment]
Hi Thong,
very good!
Please create a pull-request for this.
Thank you,
 Thomas

**Comment by huavanthong** [comment]
Hi Thomas,

This issue was resolved, if there are no comments, please help me close this ticket.

Thank you, 
Thong Hua
