### ISSUE TITLE
Unnecessary robotvscode log files are installed with Windows installer

### ISSUE THREAD

**Issue by ngoan1608** [test-fullautomation/RobotFramework_AIO#155]
Hi @test-fullautomation ,

As observation from @HolQue about unnecessary robotvscode log files are installed at `%ROBOTVSCODE%\data\user-data\logs` on Windows.
These log files should be removed from the Windows installer.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi Thong,
please solve this für our 0.9.0 release.
Thank you,
 Thomas

**Comment by ngoan1608** [comment]
This have been fixed with merged PR #156
