### ISSUE TITLE
robotframework core atest shall be part of AIO selftest

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO#157]
atest of our own robot framework core features (unknown, theading, ...) +
meaningful subset (to be identified and agreed) of the robotframework core atest must be part of the RobotFramework AIO selftest.

Result must be properly displayed in WebApp (component mapping?).

**Comment by HolQue** [comment]
Started with "log level" self test:

https://github.com/test-fullautomation/RobotFramework_AIO/pull/227

t.b.c.

From where to go from here? Is the threading self test ready to use?

**Comment by test-fullautomation** [comment]
Loglevel selftest as starting point is O.K. for me.

**Comment by test-fullautomation** [comment]
integrated in RobotFramework AIO 0.11.0
