### ISSUE TITLE
rel-tag caused error in when building jsonpreprocessor for pypi

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO#160]
rel-tag caused error in when building jsonpreprocessor for pypi.

used genpackagedoc was too old.

Maybe to be solved when genpackagedoc, pythonextensioncollection? is built/uploaded to pypi first, then all other packages.

**Comment by ngoan1608** [comment]
Hi Thomas,

Could you give more information about the error?
I have checked the [workflow to release PyPI in Github Action of python-jsonpreprocessor](https://github.com/test-fullautomation/python-jsonpreprocessor/actions/workflows/python-publish.yml). It is fine.

Besides, in the job to tag packages for pypi, `python-extensions-collection` and `python-genpackagedoc` are always tagged (to trigger the job to publish to PyPI) first.
I have also checked the [log of building jsonpreprocessor for pypi](https://github.com/test-fullautomation/python-jsonpreprocessor/actions/runs/6480693616/job/17612293214#step:5:529), the latest version of those packages are installed.

Please correct me in case I missed somethings.

Thank you,
Ngoan

**Comment by ngoan1608** [comment]
Hi Thomas,

I found the first attempt with failed log now:
https://github.com/test-fullautomation/python-jsonpreprocessor/actions/runs/6480693616/job/17596713895

The state of workflow is overwrite and I have overlooked that you have retried it.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi Ngoan,
yes, I retriggered the job, then it worked.
I assume that the job requires genpackagedoc from pypi. When this is in the build order later than other components, then the build will install an old genpackagedoc.
The fact that it worked after retriggering the job indicates that I might be correct. There was no version issue anymore.
Please check.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
solution is part of version 0.10.0
