### ISSUE TITLE
Version number handling and history

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/RobotFramework_AIO#161]
I observed the update of version numbers in files like:

https://github.com/test-fullautomation/robotframework-testsuitesmanagement/blob/develop/RobotFramework_TestsuitesManagement/version.py

Here it has to be considered that the content of these version files is also used in our documentation (e.g. GenPackageDoc uses the values). Therefore some more steps are required, to keep things aligned.

When changes are implemented and the version number and date is updated, this has to be mentioned in the component history:

https://github.com/test-fullautomation/robotframework-testsuitesmanagement/blob/develop/packagedoc/additional_docs/History.tex

When setup.py is executed also the documentation is rendered:

https://github.com/test-fullautomation/robotframework-testsuitesmanagement/blob/develop/RobotFramework_TestsuitesManagement/RobotFramework_TestsuitesManagement.pdf

Please include the corresponding PDF in the pull request.

Currently for TestsuitesManegement the version.py is on 0.7.4, but history and PDF are on 0.7.3.

Impact: PyPi announces a new version 0.7.3. The readme contains a direct link to the documentation. And the document behind this link is outdated and the users are not informed about the new features.

This is really not nice!

**Comment by test-fullautomation** [comment]
Hi Holger,
this is still open, correct?
Thank you,
 Thomas

**Comment by HolQue** [comment]
Hi Thomas,

in PyPi, in version.py and in PDF documentation the version is 0.7.4 unitary.

This is fine to me now.

**Comment by test-fullautomation** [comment]
solution is part of version 0.10.0
