### ISSUE TITLE
Environment variable shall support the path to Python site-packages

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/RobotFramework_AIO#165]
Several parts of our code require the path to Python site-packages. Unfortunately this path is not the same in Windows and Linux.

This causes long winded code like this:

```
if sPlatformSystem == "Windows":
    sInstalledPackageFolder = f"{sPythonPath}/Lib/site-packages/" + self.__dictRepositoryConfig['PACKAGENAME']
elif sPlatformSystem == "Linux":
    sInstalledPackageFolder = f"{sPythonPath}/../lib/python3.9/site-packages/" + self.__dictRepositoryConfig['PACKAGENAME']
```

with

`sPythonPath = CString.NormalizePath(os.path.dirname(sys.executable))`

Very unfavorable is also that the path under Linux contains the Python version number. Several parts of our code need to be adapted in case of a Python update comes along with a RobotFramework AIO installer. And this is not synchronized!

Therefore I would prefer to have an additional environment variable '`RobotPythonSitePackagesPath`' (additionally to '`RobotPythonPath`') containing the operating system dependent '`site-packages`' path.

**Comment by test-fullautomation** [comment]
Hi Holger,

please try if this solves your problem:

```
import site
print(site.getsitepackages())
```

or maybe better with python3 (works also with virtualenvs):
```
import sysconfig
print(sysconfig.get_paths()["purelib"])
```

Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi @huavanthong ,
after discussion with Holger I came to the conclusion that we need to create the new environment variable RobotPythonSitePackagesPath in Windows and Linux.
Drawback is that if the python version changes, then at least in Linux the set_robotenv.sh has to be adapted to the new version.
Thank you,
 Thomas

**Comment by HolQue** [comment]
Test script:

```
print()
for index, sSitePackage in enumerate(site.getsitepackages()):
   print(f"> ({index+1}) 'getsitepackages' found: '{sSitePackage}'")
   if sSitePackage.endswith('site-packages'):
      print()
      print(f"  identified: '{sSitePackage}'")
print()

sPureLib = sysconfig.get_paths()["purelib"]
print(f"'get_paths' returned: '{sPureLib}'")
print()
```

Result on Windows:

```
> (1) 'getsitepackages' found: 'D:\RobotFramework\python39'
> (2) 'getsitepackages' found: 'D:\RobotFramework\python39\lib\site-packages'

  identified: 'D:\RobotFramework\python39\lib\site-packages'

'get_paths' returned: 'D:\RobotFramework\python39\Lib\site-packages'
```

Result on Linux virtual machine:

```
> (1) 'getsitepackages' found: '/opt/rfwaio/python39/install/lib/python3.9/site-packages'

  identified: '/opt/rfwaio/python39/install/lib/python3.9/site-packages'

'get_paths' returned: '/opt/rfwaio/python39/install/lib/python3.9/site-packages'
```

Works!

But like mentioned above: It would be better to have an environment variable that strictly can be used, instead of implementing such code in every application. An environment variable also has the advantage to define paths depending on site-packages, inside JSON configuration files.

**Comment by test-fullautomation** [comment]
Hi @huavanthong .
please provide the environment variable for both, Windows and Linux with high priority.
thank you,
 Thomas
