### ISSUE TITLE
add robotframework-dependencylibrary

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO#174]
add https://pypi.org/project/robotframework-dependencylibrary/ to RobotFramework AIO installer for both, Windows and Linux build.

**Comment by huavanthong** [comment]
Hi Thomas,

I have added this library into our AIO following logs:
**Linux**
```
Collecting robotframework-dependencylibrary
  Downloading robotframework_dependencylibrary-4.0.1-py2.py3-none-any.whl (3.8 kB)
```
**Windows**
```
Collecting robotframework-dependencylibrary (from -r D:/a/RobotFramework_AIO/RobotFramework_AIO/install/python_requirements.txt (line 106))
  Downloading robotframework_dependencylibrary-4.0.1-py2.py3-none-any.whl (3.8 kB)
```

If there are not any issue, please help me close this ticket.

Thank you and best regards,
Thong Hua
