### ISSUE TITLE
build::measurement of test coverage

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO#176]
Measurement of test coverage for
- python libraries which are deployed
- keyword libraries which are deployed

**Comment by test-fullautomation** [comment]
Hi Tri,
please look into this task.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi @trimai3001 ,
what is the status of this issue?
Thank you,
 Thomas

**Comment by trimai3001** [comment]
Hi Thomas,
Regarding the issue, I currently use pytest coverage for all repositories with pytest test types. These tests are being run locally and adjusted as needed before I commit and test them in the GitHub pipeline.
Next, I will research how to run test coverage for repositories that use the robot test type.
Thank you
Tri Mai

**Comment by test-fullautomation** [comment]
Hi @trimai3001 ,

Please look into coverage. Holger found this.
https://pypi.org/project/coverage/

This seems to be a very good tool. I like that you can go into the HTML-reports and from there you get directly the code parts highlighted which are not yet tested.
If this works, then it’s really amazing.

Thank you,
 Thomas

**Comment by trimai3001** [comment]
Hi Thomas,
According to the coverage, I researched and showed Holger the prototype. He seemed happy with the coverage report last Monday, and I intended to show it to the team in the previous meeting. I am currently implementing it and will be finished soon.
BTW, could you please re-invite me to the python-microservice-base, robotframework-robotlog2rqm, and python-microservice-cleware-switch repositories? I missed your previous invitations. Sorry for the inconvenience.
Thank you,
Tri

**Comment by test-fullautomation** [comment]
integrated in 0.12.1
