### ISSUE TITLE
add version info to root directory of installation

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO#180]
the version information shall be addef to the root directory of installation.

e.g.
version.txt
containing:
RobotFramework AIO (OSS) 0.10.2

**Comment by huavanthong** [comment]
Hi Thomas,

I would like to confirm the output for this ticket. 
As my understanding, we will update the content for version.txt file and place it in the root of the installation directory as follows:
* **Windows:** C:\Program Files\RobotFramework\version.txt
* **Linux:** /opt/rfwaio/version.txt

Could you assist me in verifying this ticket?

Thank you and best regards,
Thong Hua

**Comment by test-fullautomation** [comment]
Hi Thong,
yes, you understood correct.
The idea is to have in the root directory a file which allows you quickly to identify the installed version in all OS we support.
E.g. OSD Linux is also doing this for reference. You find the version info somewhere in /opt/... folder.
Thank you,
 Thomas

**Comment by HolQue** [comment]
Hello,

small addition: In between GenMainDoc generates:

https://htmlpreview.github.io/?https://github.com/test-fullautomation/robotframework-documentation/blob/develop/RobotFrameworkAIO/Components.html

Feel free to add a link to this file wherever useful.

**Comment by huavanthong** [comment]
Hi Thomas,

This issue was resolved. Please help me close this ticket.

Thank you,
Thong Hua

**Comment by HolQue** [comment]
Underlines shout fit to the width of headline.

Not

```
Web sites:
* * * * * * * * * * * * *
```

But:

```
Web sites:
* * * * **
```

(and other)

**Comment by HolQue** [comment]
Regarding:

RobotFramework AIO Tool full version:
    https://htmlpreview.github.io/?https://github.com/test-fullautomation/robotframework-documentation/blob/develop/RobotFrameworkAIO/Components.html

This is a link to a list of components of the RobotFramework AIO (and not a link to the full version).

I would not name this "**RobotFramework AIO Tool full version:**"

And I would avoid the term "Tool". This sounds so much tiny.

Better headline for this link:

"**List of RobotFramework AIO components**"

**Comment by test-fullautomation** [comment]
solution is part of version 0.10.0
