### ISSUE TITLE
our robotframework-lsp fork must be part of pipeline and release

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO#191]
our robotframework-lsp fork must be part of pipeline and release:
https://github.com/test-fullautomation/robotframework-lsp

**Comment by test-fullautomation** [comment]
Hi @huavanthong ,
what is the status of this issue?
Thank you,
 Thomas

**Comment by ngoan1608** [comment]
Hi Thomas,

Currently, there is no change in that forked repository.
Do you still want to integrate it for this release and prepare for the future changes from that repository?

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi @milanac030988 ,
you requested this fork. Is this still required?
@huavanthong , if yes, then we need to integrate it into our pipeline. Let us wait for Cuong's answer.
Thank you,
 Thomas

**Comment by milanac030988** [comment]
Hello Thomas,
It is still required, but I haven't done the modification yet.
Thanks,
Cuong

**Comment by test-fullautomation** [comment]
Hi @milanac030988 ,
can you please create an issue for the concrete task. Then I put it into our backlog.
Thank you,
 Thomas

**Comment by huavanthong** [comment]
Hi Thomas,

I would like to update the status for this ticket.
Currently, our pipeline has been already integrated the [robotframework-lsp]( https://github.com/robocorp/robotframework-lsp) repository into our pipeline following the info at [vscode_requirement.csv](https://github.com/test-fullautomation/RobotFramework_AIO/blob/develop/install/vscode_requirement.csv)

| Publisher           | Extension           | Version |
|---------------------|---------------------|---------|
| robocorp| robotframework-lsp  | 1.11.0  |

In case that Cuong updates the **robotframework-lsp fork**, I would like provide an solution as below:

* At **robotframework-lsp fork**, I will create a release during the pipeline of robotframework-lsp fork, for an example: https://github.com/test-fullautomation/robotframework-lsp/releases
* At **RobotFramework_AIO**, I will download and integrate our release from **robotframework-lsp fork** by updating the [vscode_requirement.csv](https://github.com/test-fullautomation/RobotFramework_AIO/blob/develop/install/vscode_requirement.csv) with info below:

| Publisher           | Extension           | Version |
|---------------------|---------------------|---------|
| test-fullautomation | robotframework-lsp  | 1.11.1  |

For this solution, it ensures that any changes made in the robotframework-lsp fork will trigger the pipeline in the robotframework-lsp fork, ensuring correct release procedures.

Please take it for your information, and let me know if you have any concerns.

Thank you and best regards,
Thong Hua

**Comment by test-fullautomation** [comment]
integrated in RobotFramework AIO 0.11.0
