### ISSUE TITLE
Debian package partitioning

### ISSUE THREAD

**Issue by MarSianer1** [test-fullautomation/RobotFramework_AIO#200]
Robot AIO package includes robot fw + extensions as well as a preconfigured codium release again with extensions. Here it would be useful to split it up to at least two packages. For CI systems vscodium stuff is not of interest but only robot fw as runtime environment. So having minimum two individual packages and maybe one meta package to combine all the individuals would be useful.

**Comment by test-fullautomation** [comment]
Hi @ngoan1608 , @huavanthong ,
as per our discussion in our team meeting please check if there is a nice way to install parts of a debian package based on command line switches.
I would like to avoid to make multiple packages if possible.
Thank you,
Thomas

**Comment by test-fullautomation** [comment]
integrated in RobotFramework AIO 0.11.0
