### ISSUE TITLE
Memory footprint reduction

### ISSUE THREAD

**Issue by MarSianer1** [test-fullautomation/RobotFramework_AIO#201]
Memory footprint of installed robot aio package is > 2GB. I wonder if this is really required. At least I would guess the all __pycache__ folders and also trc files can be removed from the package. Most likely there is more to be cleaned up

**Comment by test-fullautomation** [comment]
Hi @huavanthong ,
can you please check and remove all parts which are not required.
Thank you,
 Thomas

**Comment by huavanthong** [comment]
Hi Thomas,

As my checking, the AIO package occupies 1.61GB and primarily consumes resources in two locations:
| Location | Resource |
|----------|----------|
| python39 | 0.97GB |
| -> python39/lib/ | 898MB |
| robotvscode | 610MB |

Following my observation, all the **pycache** folders belonging to **python39/lib** have already been removed from our installer. The only folder that exists is __pycache__, with a size of 0 bytes.
Please take it for your info and let me know if you have any concerns.

Thank you and best regards,
Thong Hua

**Comment by test-fullautomation** [comment]
Hi Thong,
so this means that we can't reduce anymore, except of installing only needed parts?
Thank you,
 Thomas

**Comment by huavanthong** [comment]
Hi Thomas,

I think that's correct. We've already have the ticket for installing the needed parted at https://github.com/test-fullautomation/RobotFramework_AIO/issues/200
Please take it for your information.

Thank you,
Thong Hua
