### ISSUE TITLE
Renaming of "document" folder wanted

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/RobotFramework_AIO#204]
The OSS version of the GenMainDoc configuration file can be found here:
`robotframework-documentation\maindoc\maindoc_configs\maindoc_config_OSS.json`

The BIOS version of the GenMainDoc configuration file can be found here:
`build\config\document\maindoc_config_BIOS.json`

But "`document`" is an unfavorable name for a folder containing configuration files.

I propose to rename this folder to "`documentation`".

**Comment by test-fullautomation** [comment]
already merged for version 0.11.0
