### ISSUE TITLE
Multiple corrupted unins00x.* files is still in app folder

### ISSUE THREAD

**Issue by ngoan1608** [test-fullautomation/RobotFramework_AIO#211]
Hi,

As the status of BIOS Windows runner, multiple corrupted `unins00x.dat` and corresponding `unins00x.exe` are still in {app} folder.
They should be removed along with the uninstallation.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi Ngoan,
this is solved, correct?
Thank you,
 Thomas

**Comment by ngoan1608** [comment]
Hi Thomas,

Yes, this is solved by merged  https://github.com/test-fullautomation/RobotFramework_AIO/pull/219.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
solution is part of version 0.10.0
