### ISSUE TITLE
WebApp: SelfTest version shall end with tag  if given

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO#223]
Currently selftest version is the number of the build job.

Shall be:
e.g. 3395090_0.10.0.7

**Comment by test-fullautomation** [comment]
Hi @ngoan1608 ,
what is the status of this issue?
Thank you,
 Thomas

**Comment by ngoan1608** [comment]
Hi Thomas,

This ticket is related to BIOS build pipeline.
I have created the appropriate [PR](https://gitlab-apertispro.boschdevcloud.com/robotframework-aio/main/build/-/merge_requests/91) in our Gitlab project.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
already merged in gitlab.
