### ISSUE TITLE
New Robot environment variables are not applied on Linux machine

### ISSUE THREAD

**Issue by ngoan1608** [test-fullautomation/RobotFramework_AIO#24]
Hi Nguyen,

Python and Robot Framework extensions do not work on Linux (which has installed Robot Framework AIO before) due to new environment variables setting is not applied.
The error come from the old path to **set_robotenv.sh** in _.bashrc_ file.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
solved with already merged #29
