### ISSUE TITLE
Github Windows Runner: texlive installation failed due to new version

### ISSUE THREAD

**Issue by ngoan1608** [test-fullautomation/RobotFramework_AIO#246]
Hi,

Currently Windows build job fails due to the `texlive` installation:
Error log:
```
...
Installing multirow using tlmgr
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: TeX Live 2023 is frozen
  texlive may be able to be automatically uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
The install of texlive was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\texlive\tools\chocolateyinstall.ps1'.
 See log for details.
...
```
Quick analysis: 
- choco script `chocolateyinstall.ps1` fail to execute `tlmgr` to install extra packages for `texlive`
- root cause may come from the incompatible between the recent released version of `texlive` and choco script `chocolateyinstall.ps1`

Referent job: https://github.com/test-fullautomation/RobotFramework_AIO/actions/runs/8276111793/job/22645118004
Issue has been occurred since **March 13th**.

Thank you

**Comment by test-fullautomation** [comment]
Hi Ngoan,
Thank you for the analysis.
puh... This is annoying that sometimes suddenly the pipeline doesn't work due to external changes, or new dependencies.
Is it possible to use a fix texlive version? There is no need to use always the latest versionh.
Thank you,
 Thomas

**Comment by ngoan1608** [comment]
Hi Thomas,

In previous implementation, I used specific version for texlive but there was same issue with it.
I remember that we faced issue in the same time last year, they changed the path to binary in new released version.

`tlmgr.bat` (texlive manager) is installed along with texlive and used for installing extra package.
As my observation, the script is failed to call binary file of new version (maybe path to binary change but `tlmgr.bat` is not up-to-date).

I am looking the solution to install texlive and its collections, extra packages directly from its download page instead of via `choco`.
So that we will not depends on `choco` and avoid further issue(s) such as this one.
 
I will update on this ticket.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi Ngoan,
sounds good! I'm sorry that you have to spend this effort.
Thank you,
 Thomas

**Comment by ngoan1608** [comment]
Hi Thomas,

No problem for me!
This is my job to stabilize our build pipeline.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
integrated in RobotFramework AIO 0.11.0
