### ISSUE TITLE
Tag tool is required for separated OSS release

### ISSUE THREAD

**Issue by ngoan1608** [test-fullautomation/RobotFramework_AIO#27]
Hi,

Tag tool should be a part of this repo for OSS release.

Thank you,
Ngoan

**Comment by ngoan1608** [comment]
Hi Thomas,

Please refer the current status of this issue: 
- The change in Github was available in feature branch https://github.com/test-fullautomation/RobotFramework_AIO/tree/ntd1hc/feat/tag-tool-is-required-for-oss-release.
- But it requires the change in BIOS due to tag tool location changed (moved to this repo instead of **build**). I am working on it

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi Ngoan,
very good!
Please inform me when inform me when finished.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi Ngoan,
I merged #64 , so this can be closed?
Thank you,
 Thomas

**Comment by ngoan1608** [comment]
Hi Thomas,

This ticket can be close now.

Thank you,
Ngoan
