### ISSUE TITLE
Execute Appium selftest in build pipeline

### ISSUE THREAD

**Issue by ngoan1608** [test-fullautomation/RobotFramework_AIO#273]
Hi,

The Appium selftest execution should be a part of selftest jobs of our build pipeline:
- Install Emulator (with appropriate api version) and run it  up for Appium selftest within test jobs.
- Add Appium selftest into our aio-test-trigger for test execution

Thank you,
Ngoan

**Comment by trimai3001** [comment]
The emulator was installed and started when running the Appium self-test.
