### ISSUE TITLE
Known issue of robotframework-appiumlibrary due to incompatible version of current selenium versions

### ISSUE THREAD

**Issue by ngoan1608** [test-fullautomation/RobotFramework_AIO#274]
Hi,

There is a known incompatible  issue of **robotframework-appiumlibrary** due to **selenium**>=**4.17.0**.
https://github.com/serhatbolsu/robotframework-appiumlibrary/issues/415
https://github.com/serhatbolsu/robotframework-appiumlibrary/issues/413

It has been fixed as following merged PR in [robotframework-appiumlibrary](https://github.com/serhatbolsu/robotframework-appiumlibrary) but is not released as new version yet.
https://github.com/serhatbolsu/robotframework-appiumlibrary/pull/414/commits/c0d09e3bab344fdccefbb00d47c333665ac1a41e

This issue causes error when using below keywords:
- [Swipe By Percent](https://serhatbolsu.github.io/robotframework-appiumlibrary/AppiumLibrary.html#Swipe%20By%20Percent)
- [Click Text](https://serhatbolsu.github.io/robotframework-appiumlibrary/AppiumLibrary.html#Click%20Text)
- ...

While waiting for new release from [robotframework-appiumlibrary](https://github.com/serhatbolsu/robotframework-appiumlibrary), temporary solution is downgrade selenium to version 4.16.0 (deprecated desired_capabilities was removed from [selenium-4.17.0](https://github.com/SeleniumHQ/selenium/releases/tag/selenium-4.17.0))

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
this is solved with new appium in 0.12.1
