### ISSUE TITLE
additional python libraries required (asciidoxy, pyqt5, dotted-dict and QtAwesome)

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO#279]
The following pyhton libraries shall be added to RobotPython:
PyQt5: https://pypi.org/project/PyQt5/
qtawesome: https://pypi.org/project/QtAwesome/
asciidoxy: https://pypi.org/project/asciidoxy/
dotted-dict: https://pypi.org/project/dotted-dict/

**Comment by huavanthong** [comment]
Hi Thomas, 

I have integrated the libraries following the pull request above.
Log files can be found at https://github.com/test-fullautomation/RobotFramework_AIO/actions/runs/9058731691/job/24884911941

Please take it for your info.

Thank you and best regards,
Thong Hua

**Comment by namsonx** [comment]
Hello Thomas, Hello Thong,

As I informed you via email the dotted-dict package will check the convention of JSON key names, so it causes the error message “ValueError: Key "global" is a reserved keyword.” while executing our selftest.
Now we will use the pydotdict package as temporary solution until we can find another dotdict as final solution.

Hi @huavanthong, please replace package dotted-dict by pydotdict (https://pypi.org/project/pydotdict/)

Thank you,
Son

**Comment by test-fullautomation** [comment]
Released with RobotFramework AIO 0.12.0
