### ISSUE TITLE
release-info tool extention

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO#288]
The release info tool shall accept a semicolon separated list of versions.
e.g.  `"0.11.1.; 0.11.2.;0.12.0.; " : [ ...`

Content shall appear in all corresponding versions (`startswith` ...)

**Comment by HolQue** [comment]
Realized in
https://github.com/test-fullautomation/RobotFramework_AIO/pull/293

**Comment by test-fullautomation** [comment]
integrated in 0.12.1
