### ISSUE TITLE
describe workflow how to integrate a new repository

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO#291]
describe complete workflow how to integrate a new repository.

In the meanwhile lot of things have to be done when a new repository is integrated.
Usually do this interatively during multiple builds.

Goal is to do all in one that iterations are not required.

Documentation shall be part of main-documentation
https://github.com/test-fullautomation/robotframework-documentation

There can be a new chapter "For RobotFramework AIO Developers" where this is a sub-chapter.

**Comment by test-fullautomation** [comment]
see also: https://github.com/test-fullautomation/robotframework-documentation/pull/70#issuecomment-2183008252

**Comment by huavanthong** [comment]
Integrated in RobotFramework AIO 0.13.0
