### ISSUE TITLE
Android SDK and other version information missing

### ISSUE THREAD

**Issue by MarSianer1** [test-fullautomation/RobotFramework_AIO#295]
Robot-AIO includes Android SDK and other devtools but neither release note nor version file contains the information about used/integrated versions

**Comment by test-fullautomation** [comment]
Hi @huavanthong ,
please look into this issue.
version.txt should hold additional meaningful version numbers.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi @huavanthong ,
what is the status of this issue?
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
part of 0.13.0
