### ISSUE TITLE
Python code coverage module wanted

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/RobotFramework_AIO#299]
To support Python code coverage computation I suggest to integrate

https://pypi.org/project/coverage/

**Comment by trimai3001** [comment]
the module was integrated

**Comment by HolQue** [comment]
`coverage` not part of 0.13.0.23 (windows:build, BOSCH internal version)

**Comment by test-fullautomation** [comment]
Hi @trimai3001 ,
what happened?
Please add coverage for 0.13.1.
Thank you,
 Thomas

**Comment by trimai3001** [comment]
Hi @test-fullautomation,
Sorry about the mistake in my last commit where I missed some files, which caused the test coverage not to run.
I have created a new pull request to fix the issue: https://github.com/test-fullautomation/RobotFramework_AIO/pull/371
Thank you for understanding,
Tri

**Comment by test-fullautomation** [comment]
Hi Tri,
O.K. no problem.
I already merged #371

Thank you,
 Thomas
