### ISSUE TITLE
introduction of fully automated continous test (CT)

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO#30]
Continuous test shall be executed as part of the pipelines for all repositories using [test-trigger](https://github.com/test-fullautomation/RobotFramework_AIO/tree/develop/test/aio-test-trigger)

in case of dev/rel tag the test result shall be published in the WebApp.

Bosch internal WebApp instance existing.
OSS WebApp to be setup.

**Comment by ngoan1608** [comment]
Hi Thomas,

Please refer the current status of this issue:
- Change in OSS has been merged.
- The BIOS pipeline is nearly completed (download built artifacts, AIO installations are fine) now with some adaptions for executing aio-testtrigger properly.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
CT successfully introduced with 0.7.0
