### ISSUE TITLE
Modification of version number access wanted

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/RobotFramework_AIO#301]
Currently the build process takes the component version number out of a file named `version.py`. This file name is a requirement.

But in my opinion it would be better to be more flexible here. For example the Prometheus interface library is a one-file-tool that can also store the version number within itself. It is not nice to have the need to add an additional file only for providing the version number. It would also be a Python file, placed in the same folder and the version is defined in the same way.

This should not make a difference.

My proposal is to introduce a dictionary in the build scripts. Keys are the component names or the repository names. And the key values are the file names in which the version is stored.

This solution would allow us to be more flexible and would prevent us from having the need to add files that are not really required in my opinion.

Reference:
https://github.com/test-fullautomation/robotframework-prometheus/pull/14

**Comment by test-fullautomation** [comment]
Hi Holger,
your requirement is not clear to me.
Let us talk about this.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
integrated in 0.12.1
