### ISSUE TITLE
release tool must generate relesae note adapted to version information

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO#316]
The generated release notes contain in many places version information which is based on the tag.

e.g 
Texts: rel/aio/0.12.1.4
Links: https://github.com/test-fullautomation/robotframework-qconnect-base/pulls?q=is%3Apr+is%3Aclosed+label%3A0.12.1

...
must be automatically adapted to the version information provided by the tag which triggered dev/rel build.

**Comment by ngoan1608** [comment]
Integrated in RobotFramework AIO 0.13.0
