### ISSUE TITLE
github Release Text must contain content of release_info files

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO#324]
Currently Release Text is (quite) empty:
https://github.com/test-fullautomation/RobotFramework_AIO/releases/tag/rel%2Faio%2F0.12.1.5

Must be:
Must contain summary of changes noted in release_info files

**Comment by test-fullautomation** [comment]
Hi Thong,
please look into this.
Thank you,
 Thomas

**Comment by ngoan1608** [comment]
Integrated in RobotFramework AIO 0.13.0
