### ISSUE TITLE
robotframework-uds: setup basic infrastructure

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO#334]
robotframework-uds:      
add infrastructure for setup.py, documentation and release_info

_Originally posted by @test-fullautomation in https://github.com/test-fullautomation/robotframework-uds/pull/2#pullrequestreview-2229625765_

**Comment by HolQue** [comment]
Done with https://github.com/test-fullautomation/robotframework-uds/pull/6
