### ISSUE TITLE
Tutorial must be part of initial preconfigured workspace

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO#34]
Tutorial must be part of initial preconfigured workspace for all OS.

**Comment by tranhoangnguyen193** [comment]
Hi team.
I fixed the issue in above pull request.

**Comment by tranhoangnguyen193** [comment]
TODO: Filter only folder with \d\d\d_{string}

**Comment by test-fullautomation** [comment]
Hi Nguyen,
what is the status here? #49 copies all files. When do I get a pull-request?
Thank you,
  Thomas

**Comment by test-fullautomation** [comment]
solved with 0.7.0
