### ISSUE TITLE
Command line extensions for Robot Framework executions in VS Codium

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/RobotFramework_AIO#38]
Currently log files have a fix name and are placed within the test suite folder automatically. A log file in text format is not available. This is an unfavorable limitation.

Therefore the following extensions would be useful:
* Add the -b option to get log files in text format also
* Give users the possibility to define the name of all log files
* Give users the possibility to define the log file folder (this includes the automated generation of subfolders
  containing runtime informations like a timestamp or the test suite name).

We need to find a possibility to configure these extensions in VS Codium.

**Comment by HolQue** [comment]
First step done with:
https://github.com/test-fullautomation/RobotFramework_AIO/pull/39

Next step (after integration): Documentation

**Comment by test-fullautomation** [comment]
solved and alredy merged with #39
