### ISSUE TITLE
launchers to be selected in project dialogue inno setup

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO#43]
Similar to TML the innosetup dialogue shall allow to make a project dependent preconfiguration.

Start are the launchers.
1. entry is "general"
2. entry is "Daimler CIVIC",
3. ...

Accoding to the chosen setting the proper launchers shall be copied to the related VSCodium directory.

This gives e.g. easy access to launch a run for different variants of a project.

**Comment by tranhoangnguyen193** [comment]
TODO:

0. Provide infrastructure to do this
1. Make installer copy corecsponding json config file to target folder.
2. How should we handle internal and external (OSS) config
3. ...

**Comment by test-fullautomation** [comment]
For 0.7.0 version the entry "general" with generic launchers + inno setup and deb infrastructure is enough.

Further project entries come later.

**Comment by tranhoangnguyen193** [comment]
Hi team.
The requested issue was supported in pull request #50 . Currently we can make project config in folder config/projects. (Add new projects in file config/projects/project.json and add configuration files in configured folder)

**Comment by test-fullautomation** [comment]
initial integration done with #50
