### ISSUE TITLE
Make RobotFramework AIO documentation and tutorial available in VS Codium

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/RobotFramework_AIO#44]
1. Build process should copy all PDFs from
   `robotframework-documentation\book`
   to a new '`documentation`' subfolder of VS Codium default workspace

2. To enable a preview of PDF files in VS Codium the following extension needs to be installed: `vscode-pdf`

3. also the tutorial shall be preloaded as part of the initial workspace.

This solution might be better than to let the users search for every documentation separately in site-packages of the
Python installation.

**Comment by test-fullautomation** [comment]
Hi Nguyen,
please look into this.
Thank you,
 Thomas

**Comment by tranhoangnguyen193** [comment]
Hi team,
I fixed the issue in above pull request.

**Comment by tranhoangnguyen193** [comment]
TODO: Add only Roboframework-reference.pdf file in book folder.
Add the vscode-pdfextension too.

**Comment by test-fullautomation** [comment]
Hi Nguyen,
what is the status here? The pull-request #49 copies the whole book folder?
When do I get an update?
Thank you,
 Thomas

**Comment by tranhoangnguyen193** [comment]
Hi Thomas. The document was filtered on pull request #50

**Comment by test-fullautomation** [comment]
solved and already merged  with #50
