### ISSUE TITLE
Update notification of VS Codium

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/RobotFramework_AIO#45]
Some moments after start of VS Codium (under Windows) a notification popup appears, telling about an available update.

This is unfavorable - because I assume that we do not want the users to modify a preconfigured development environment.
Therefore this popup has to be clicked away after every start of VS Codium.

I would prefer to have this notification mechanism deactivated.

**Comment by tranhoangnguyen193** [comment]
Fixed in above pull request

**Comment by test-fullautomation** [comment]
already solved and merged with #44
