### ISSUE TITLE
vscode-jsonp integration in build process

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO#81]
https://github.com/test-fullautomation/vscode-jsonp shall be integrated into build process.

Bosch-internal and OSS-Version shall integrate preconfigured jsonp plugin into VSCodium.

**Comment by test-fullautomation** [comment]
Hi Ngoan,
we mirror now the repository. Does our toolchain integrate the version from the repository into our RobotFramework AIO release package? 
Where is the code for Windows and Linux? Maybe I overlooked it in my reviews?
Thank you,
 Thomas

**Comment by ngoan1608** [comment]
Hi Thomas,

The installation of **vscode-jsonp** extension was added in _install.sh_ script (for both Windows and Linux) as below merged PR:
https://github.com/test-fullautomation/RobotFramework_AIO/pull/85/files#diff-65845b92f5ee07169285791a57b33dd35b5792a60a4d436d2c761324a492a2c1

The **vscode-jsonp** repo is cloned together with other repos and _install.sh_ script used the built extension file _*.vsix_ from that repo.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi Ngoan,
very good, I found now where it is copied from the vscode-jsonp repo.
Thank you, 
 Thomas
