### ISSUE TITLE
default lauch file shall configure internal terminal and logfolder for logfiles

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO#83]
Hi Nguyen,

this is related to 0.7.0.6:
default lauch file shall configure internal terminal and logfolder for logfiles

Please integrate the launch file from Holger as default launch file.

With this change please also remove the robot_config_template.json file. One config file in the config folder is enough.

Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi Nguyen,
please provide this change as soon as possible.
I wait that I can build 0.7.0.7 version.

Thank you,
 Thomas

**Comment by HolQue** [comment]
Configured internal terminal and logfolder for logfiles
[launch.json.txt](https://github.com/test-fullautomation/robotframework-testsuitesmanagement/files/11030936/launch.json.txt)

**Comment by test-fullautomation** [comment]
part of 0.7.05
