### ISSUE TITLE
automation shall update pypi

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO#84]
our CI automation shall update pypi, too
- base is a new configuration file where components to be updated in pypi are configured
- tag rel/<current_componentversion> need to be created per repository
- no automatic update if rel/<current_componentversion> is already existing.
  This would mean that the latest component version is already available in pypi

**Comment by ngoan1608** [comment]
1. Create/maintain Github workflow in repos to create Github Release and publish packages to PyPI
    - [x] [python-extensions-collection](https://github.com/test-fullautomation/python-extensions-collection)
    - [x] [python-genpackagedoc](https://github.com/test-fullautomation/python-genpackagedoc)
    - [x] [python-jsonpreprocessor](https://github.com/test-fullautomation/python-jsonpreprocessor)
    - [x] [python-pytestlog2db](https://github.com/test-fullautomation/python-pytestlog2db)
    - [x] [python-microservice-base](https://github.com/test-fullautomation/python-microservice-base)
    - [x] [python-microservice-cleware-switch](https://github.com/test-fullautomation/python-microservice-cleware-switch)
    - [x] [robotframework-extensions-collection](https://github.com/test-fullautomation/robotframework-extensions-collection)
    - [x] [robotframework-qconnect-base](https://github.com/test-fullautomation/robotframework-qconnect-base)
    - [x] [robotframework-testsuitesmanagement](https://github.com/test-fullautomation/robotframework-testsuitesmanagement)
    - [x] [robotframework-robotlog2db](https://github.com/test-fullautomation/robotframework-robotlog2db)
    - [x] [robotframework-robotlog2rqm](https://github.com/test-fullautomation/robotframework-robotlog2rqm)

2. New job/step in build pipeline (OSS or BIOS) to tag repos with **rel/<current_componentversion>**
    - [x] Update `git-tag` tool to allow tag **rel/x.x.x.x** for Github repos
    - [x] Update build pipeline to add new job to tag repos for publishing to PyPI

**Comment by test-fullautomation** [comment]
manually verified upload to pypi:
- [x] [python-extensions-collection](https://github.com/test-fullautomation/python-extensions-collection)
- [x] [python-genpackagedoc](https://github.com/test-fullautomation/python-genpackagedoc)
- [x] [python-jsonpreprocessor](https://github.com/test-fullautomation/python-jsonpreprocessor)
- [x] [python-pytestlog2db](https://github.com/test-fullautomation/python-pytestlog2db)
- [ ] [~~python-microservice-base~~](https://github.com/test-fullautomation/python-microservice-base)
- [ ] [~~python-microservice-cleware-switch~~](https://github.com/test-fullautomation/python-microservice-cleware-switch)
- [ ] [robotframework-extensions-collection](https://github.com/test-fullautomation/robotframework-extensions-collection)
- [ ] [robotframework-qconnect-base](https://github.com/test-fullautomation/robotframework-qconnect-base) 
- [ ] [robotframework-testsuitesmanagement](https://github.com/test-fullautomation/robotframework-testsuitesmanagement)
- [ ] [robotframework-robotlog2db](https://github.com/test-fullautomation/robotframework-robotlog2db)
- [ ] [robotframework-robotlog2rqm](https://github.com/test-fullautomation/robotframework-robotlog2rqm)

**Comment by ngoan1608** [comment]
Update:
python-microservice-* repos is now removed from configuration for publishing to PyPI.

**Comment by ngoan1608** [comment]
Done with merged PR https://github.com/test-fullautomation/RobotFramework_AIO/pull/89 and `Publish <package> to PyPI` workflow on corresponding repositories.

**Comment by test-fullautomation** [comment]
solved and already merged with #89
