### ISSUE TITLE
python-microservice* need to be removed from genpackagedoc configuration

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO#88]
Up to now python-microservice* documentation is empty (only dummy), 
therefore it need to be removed from the genpackagedoc configuration for version 0.8.0

Correction from HolQue:

python-microservice* documentation needs to be removed from GenMainDoc configuration.

**Comment by ngoan1608** [comment]
This ticket is done with above merged PR and can be closed.
