### ISSUE TITLE
Android support and Appium integration

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO#96]
Android testing shall be supported.

- Appium shall be part of RobotFramework AIO
- adb shall be part of RobotFramework AIO
- AppiumLibrary shall be part of RobotFramework AIO

**Comment by test-fullautomation** [comment]
Hi Thong,
please look into this.
For windows this should be an (by default off) option to install android tools.
Thank you,
 Thomas

**Comment by ngoan1608** [comment]
Hi,

There are some notes from my side when experimenting with [Appium Library for robotframework](https://docs.robotframework.org/docs/different_libraries/appium):
- Appium version 2.x installation requires [Node.js](https://nodejs.org/) (install via `npm`). `UiAutomator2` is installed as driver of `appium`.
- Python and robotframework libraries should be updated to latest ones to avoid incompatible issue 
`Appium-Python-Client` should be `3.x.x`
`robotframework-appiumlibrary` should be `2.x.x`
I used **Appium-Python-Client==3.1.1** and **robotframework-appiumlibrary==2.0.0**, it works fine.
- Appium is currently not started by [`robotframework-appiumlibrary`](https://serhatbolsu.github.io/robotframework-appiumlibrary/AppiumLibrary.html), user has to start it manually before executing robot test case. 

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
integrated in RobotFramework AIO 0.11.0
