### ISSUE TITLE
Some findings in RobotFramework_AIO repository README.md

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/RobotFramework_AIO#98]
The `README.md` contains a picture with following text: "**Build RoboFramework AIO packages failing**" (that is a link to build_robotframework_aio.yml).

I wonder about the "failing" in the picture text.

Also the wording can be improved.

Not:
"Preconditions

When building RobotFramework AIO package, the document is also generated with GenPackageDoc using TeX Live tool.

So, Tex Live should be installed first. The full collection is recommended when installing texlive to avoid issue when generating document but it will take long time for the installation.
"

But:
"
Preconditions

Building a RobotFramework AIO installer includes rendering the documentation. This requires the availability of some additional applications that have to be installed at first.

(add more details like already done, but without paragraphs between the sentences)

"

Not: Download and install python 
But: Download and install Python (required version ...)

Not: The workflow to build RobotFramework AIO package is available in Github Actions os this repo as below:
But: The workflow to build RobotFramework AIO packages is available in "Github Actions" of this repository:

Not: There are 2 build jobs for both environment Windows and Linux, the building jobs contains following main steps:
But: There are build jobs available for both environments Windows and Linux. These build jobs contain the following main steps:

Not: Upload built package : save the built package as workflow artifactory
But: Upload build package : save the build package as workflow artifactory

Not: Currently, there are 2 available runners (GitHub-hosted) for build pipeline:
But: Currently, there are two runners (GitHub-hosted) available for build pipelines:

Not: We are always searching support and you are cordially invited to help to improve Robot Framework AIO.
But: We are always interested in support and you are cordially invited helping us to improve the Robot Framework AIO.

**Comment by test-fullautomation** [comment]
Hi Ngoan,

I saw often that build / test-information is at the top of the readme. I wonder that you put it into the center.

Thank you,
 Thomas

**Comment by ngoan1608** [comment]
Solved with merged PR #101

**Comment by test-fullautomation** [comment]
solved and already merged with #101
